# Workflow to create a release when a new tag is created
# It will generate the release on GitHub and attach the packages

name: Release

# on:
#   push:
#     tags:
#       - '*'
on: push

jobs:

  build-archive:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/touche

      - name: Build archive
        run: |
          cd ${{ github.workspace }}/touche
          npm run archive

      - name: Generate checksum
        run: |
          sha256sum archive.tar.gz > ARCHIVE-SHA256SUM

      - name: Upload archive artifact
        uses: "actions/upload-artifact@v2"
        with:
          name: "archive.tar.gz"
          path: "${{ github.workspace }}/archive.tar.gz"

      - name: Upload archive checksum artifact
        uses: "actions/upload-artifact@v2"
        with:
          name: "ARCHIVE-SHA256SUM"
          path: "${{ github.workspace }}/ARCHIVE-SHA256SUM"

  deb-package:
    runs-on: ubuntu-20.04
    needs: [ build-archive ]
    env:
      target_docker_image: debian:buster-backports
      target_distribution: buster
    strategy:
      matrix:
        target_arch: ["amd64", "armhf", "arm64"]
    steps:
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: Download archive
        uses: "actions/download-artifact@v2"
        with:
          name: archive.tar.gz

      - name: Extract archive
        run: |
          tar -xf archive.tar.gz

      - name: Copy node_modules to debian/missing-sources
        run: |
          mkdir -p debian/missing-sources
          cp -r node_modules debian/missing-sources

      - name: Patch target distribution in Debian changelog
        # touche (x.y.z) DISTRO; urgency=medium
        # -z to replace only the first occurrence
        # -i to update the file
        # ([)] ) - Group 0, find the first ") "
        # (\w+)  - Group 1, find a word (DISTRO)
        # \1${{ env.target_distribution }} - Replace group 1 with the target distribution name
        run: |
          sed -zri "s/([)] )(\w+)/\1${{ env.target_distribution }}/" ${{ github.workspace }}/debian/changelog

      - name: Build Debian package
        uses: pi-top/action-debian-package@v0.2.2
        with:
          source_directory: "${{ github.workspace }}"
          artifacts_directory: "${{ github.workspace }}/artifacts"

          docker_image: ${{ env.target_docker_image }}
          distribution: ${{ env.target_distribution }}
          target_architecture: ${{ matrix.target_arch }}

          lintian_opts: "--dont-check-part nmu --no-tag-display-limit --display-info --show-overrides"
          # Package uses latest packaging syntax and Lintian opts/tags
          dpkg_buildpackage_opts: "--no-sign --no-check-builddeps --post-clean"

      - name: Upload Debian package artifacts
        uses: "actions/upload-artifact@v2"
        with:
          name: "${{ env.GITHUB_REPOSITORY_NAME }}-${{ env.GITHUB_REF_NAME }}-${{matrix.target_arch}}-deb"
          path: "${{ github.workspace }}/artifacts/${{ env.GITHUB_REPOSITORY_NAME }}_${{ env.GITHUB_REF_NAME }}_${{matrix.target_arch}}.deb"
